### ISSUE TITLE
Attach release builds to release notes automatically

### ISSUE THREAD

**Issue by ns-rse** [claritychallenge/clarity#137]
Currently when releases are made with tagged commits `pyclarity` is built and packaged and released automatically to PyPI (courtesy of `~/.github/workflows/pypi.yaml`).

It should be possible to upload the artifacts (a source distribution `pyclarity-#.#.#.tar.gz and a wheel `pyclarity-0.2.0-py3-none-any.whl`) and attach to the release automatically.

A possible solution is to use [this GitHub Action](https://github.com/Roang-zero1/github-upload-release-artifacts-action) which would require `args: "buiild/"` since this is the location of built artifacts.

```
    - name: Upload release artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v2
      with:
        args: "build/"
```
