### ISSUE TITLE
Enable pylint in pre-commit checks

### ISSUE THREAD

**Issue by ns-rse** [claritychallenge/clarity#182]
We have linted the code base using [pylint](https://pylint.pycqa.org/en/latest/) (see issue #42 and PR #43) however we do not enforce `pylint` checks against new commits.

We can do this by incorporating a `pylint` hook into [`pre-commit`](https://pre-commit.com) which will carry through to the [`pre-commit.ci`](https://pre-commit.ci) GitHub Action.

In instances like this we should use a `local` hook because using the one provisioned by the [PyCQA](https://github.com/PyCQA/pylint) will not include the necessary packages required to perform the checks. This can be achieved using the following snippet which will use the existing `.pylintrc` configuration.

```yaml
  - repo: local
    hooks:
      - id: pylint
        args: ["--rcfile=.pylintrc"]
        name: Pylint
        entry: python -m pylint
        language: system
        files: \.py$
```
