### ISSUE TITLE
Increase pyupgrade version

### ISSUE THREAD

**Issue by jonbarker68** [claritychallenge/clarity#260]
In the pre-commit hook file, pyupgrade is using --py37-plus but we can now increase this to --py38-plus

i.e., 

```
- repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
```
