### ISSUE TITLE
Forthcoming NumPy2.0 release

### ISSUE THREAD

**Issue by ns-rse** [claritychallenge/clarity#358]
Numpy2 is due to be released early later this year (first release candidate is scheduled 2024-02-01).

This may introduce some breaking changes, a broad overview is available [here](https://pythonspeed.com/articles/numpy-2/).

Mentioned in that article is that `scikit-image` has issues, which is indirect because the package has an optional dependency on `matplotlib` (I've discovered this whilst working on `skan` issues).

The official [NumPy 2.0 migration guide — NumPy v2.0.dev0 Manual](https://numpy.org/devdocs/numpy_2_0_migration_guide.html) suggests that `ruff` can be leveraged to address the mentioned changes under [Ruff Plugin](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin).

To which end we may be able to check and anticipate any breaking changes by adding the following to `pyproject.toml` :

```toml
[tool.ruff.lint]
extend-select = ["NPY201"]
preview = true
```

Although I've tried this on another project and `pre-commit` complained that `tool.ruff.lint` was a duplicate (I think because I have other `tool.ruff.lint.*` sections already defined). What worked for me was adding the following...

```toml
[tool.ruff]
...
lint.extend-select = ["NPY201"]
preview = true
```
After adding this the checks should be run using the `pre-commit` hook

```bash
pre-commit run --all-files ruff
```
